# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Scriptor-artis Website
    url: https://www.scriptor-artis.com
  - name: Clavus API
    url: https://api-v2.clavus.io/health
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Clavus Website (Public 1)
    url: https://www.clavus.io
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Clavus Website (Public 1)
    url: https://tzar.clavus.cloud
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Clavus Website (C1)
    url: $CLIENT1
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Clavus Website (C2)
    url: $CLIENT2
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Whitemark systems
    url: http://wm.clavus.io/
  - name: Tzar Website
    url: https://www.tzar.fr
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Tzar API
    url: https://api.tzar.fr/health
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: SMTP 1 (clavus.io)
    check: "tcp-ping"
    url: 163.172.93.27
    port: 465
  - name: SMTP 2 (private)
    check: "tcp-ping"
    url: 163.172.44.120
    port: 465
  - name: Office A
    url: https://office-a.clavus.io/welcome/
  - name: Office B
    url: https://office-b.clavus.io/welcome/
  - name: Meet (visio)
    url: https://meet.clavus.io/
  - name: Webmail 1
    url: https://webmail.clavus.io
  - name: P1 Server
    check: "tcp-ping"
    url: $PRODUCTION1
    port: 3001
  - name: P2 Server
    check: "tcp-ping"
    url: $PRODUCTION2
    port: 3001
  - name: P3 Server
    check: "tcp-ping"
    url: $PRODUCTION3
    port: 3001
     

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.scriptor-artis.fr
  # baseUrl: /your-repo-name
  logoUrl: https://chat-pictures-prod.s3.fr-par.scw.cloud/6a63b5c3-5c7b-4d09-a924-dbec9ef12b21
  name: Scriptor-artis
  introTitle: "Services **Upptime**"
  introMessage: "Affiche l'état des serveurs de scriptor-artis."
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
