# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Clavus API
    url: https://api-v2.clavus.io
  - name: Clavus Website (1)
    url: https://www.clavus.io
  - name: Clavus Front-end (2)
    url: https://tzar.clavus.cloud
  - name: Tzar Website
    url: https://www.tzar.fr
  - name: Tzar API
    url: https://api.tzar.fr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://clavus.io/static/svg/homepage/logo.svg
  name: Upptime
  introTitle: "Clavus monitoring **Upptime**."
  introMessage: "Cette page affiche l'état des services de scriptor-artis"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
